name: Actions develop
on: 
  push:
    branches:
      # - '*'
      # - '!master'
      # - '!develop'
      - 'feature/**'

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    name: Create branches for Pull Request
    steps:
      - name: Set output 
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - run: echo "🎉 El evento se ejecutó en la rama ${{ steps.vars.outputs.short_ref }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      
      - name: Create Pull Request

        uses: shubhsherl/create-catchup-pr@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{github.repository}}

          SOURCE_BRANCH: "${{ steps.vars.outputs.short_ref }}"
          TARGET_BRANCH: "develop"
          TITLE: '[Pull request - ${{ github.actor }}] Into develop from ${{ steps.vars.outputs.short_ref }}'
          BODY: | 
            Update featura
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            
            [1]: https://github.com/InterfazProductosDigitales     
